class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
class Main implements Hello { void hello(int i) {System.out.println(i)} }
